CREATE DATABASE dbProjetoCad;

USE dbProjetoCad;

CREATE TABLE tbUsuarios (
Id INT AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(40) NOT NULL ,
Email VARCHAR(225) NOT NULL UNIQUE,
Senha VARCHAR(225) NOT NULL
);

CREATE TABLE tbProdutos (
Id INT AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(40) NOT NULL,
Descricao VARCHAR(255),
Preco DOUBLE NOT NULL CHECK(Preco >=0) ,
Quantidade INT NOT NULL CHECK(Quantidade >=0)
);